services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Expose backend on port 3000 
    depends_on:
      - mysql
      - redis
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=testdb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: sh -c "sleep 10 && ./main"
    
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.4-alpine
    user: root
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

volumes:
  mysql_data:
  redis_data: